services:
  - type: web
    name: nocap-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --timeout 300 --workers 2 --threads 4 --worker-class gthread --log-level=debug --access-logfile - --error-logfile -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "nocap-backend.onrender.com,no-cap-sage.vercel.app"

